# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  release:
    types: [published]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build linux arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -o viam-revolution-pi -v .

    - name: Package
      run: tar -zcf viam-revolution-pi.tar.gz viam-revolution-pi

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test
        run: go test -v ./...

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'release'
    steps:
    - name: Upload
      uses: viamrobotics/upload-module@main
      with:
        module-path: viam-revolution-pi.tar.gz
        namespace: viam-labs
        platform: linux/arm64
        version: ${{ github.ref_name }}
        cli-config-secret: ${{ secrets.cli_config }}
