# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o viam-revolution-pi -v .

    - name: Test
      run: go test -v ./...

    - name: Package
      run: tar -zcf viam-revolution-pi.tar.gz viam-revolution-pi

    - name: Upload
      uses: viamrobotics/upload-module@main
      with:
        module-path: viam-revolution-pi.tar.gz
        namespace: viam-labs
        platform: linux/arm64
        version: ${{ github.ref_name }}
        cli-config-secret: ${{ secrets.cli_config }}
